routes/admin.php
<?php

Route::group(['prefix' => 'admin', 'middleware' => ['role:admin']], function() {

	Route::get('home',[
	    'as'    =>  'admin.home',
	    'uses'  =>  'Admin\HomeController@index'
	]);

	/**
	 * route change session
	 */
	Route::get('changeSession/{id}',[
	    'as'    =>  'admin.changeSession',
	    'uses'  =>  'Admin\ReportController@changeSession'
	]);

	Route::resource('reports', 'Admin\ReportController', ['except' => ['show']]);
	Route::get('downloadKuisioner/{id}',[
	    'as'    =>  'admin.downloadKuisioner',
	    'uses'  =>  'Admin\ReportController@downloadKuisioner'
	]);

	Route::resource('kotas', 'Admin\KotaController', ['except' => ['show']]);
	Route::resource('stores', 'Admin\StoresController');
	Route::resource('positions', 'Admin\PositionController');
	Route::resource('fisiks', 'Admin\FisiksController');
	Route::resource('reportstore', 'Admin\ReportStoreController');

	/**
	 * route fisik store
	 */
	Route::get('/fisikstores/store','Admin\FisikStoreController@stores')->name('admin.fisikstores.store');
	Route::get('/fisikstores/{code_store}','Admin\FisikStoreController@index')->name('admin.fisikstores.index');
	Route::get('/fisikstores/create/{code_store}','Admin\FisikStoreController@create')->name('admin.fisikstores.create');
	Route::post('/fisikstores/post/{code_store}','Admin\FisikStoreController@store')->name('admin.fisikstores.simpan');
	Route::delete('/fisikstores/destroy/{id}','Admin\FisikStoreController@destroy')->name('admin.fisikstores.destroy');


	/**
	 * route crud staff
	 */
	Route::get('/staffs/stores/','Admin\StaffController@stores')->name('admin.staffs.stores');
	Route::get('/staffs/{code}','Admin\StaffController@index')->name('admin.staffs.index');
	Route::get('/staffs/create/{code}','Admin\StaffController@create')->name('admin.staffs.create');
	Route::post('/staffs/store/{code}','Admin\StaffController@store')->name('admin.staffs.store');
	Route::get('/staffs/edit/{id}','Admin\StaffController@edit')->name('admin.staffs.edit');
	Route::put('/staffs/update/{id}','Admin\StaffController@update')->name('admin.staffs.update');
	Route::delete('/staffs/delete/{id}','Admin\StaffController@destroy')->name('admin.staffs.delete');

	/**
 * route kaategori parameter posisi
	 */
	Route::get('posisi/parameter_category/{id_posisi}','Admin\ParameterCategoryPositionController@create')
		   ->name('admin.posisi.parameter_category.position');
	Route::post('posisi/parameter_category/store/{id_posisi}','Admin\ParameterCategoryPositionController@store')
		   ->name('admin.posisi.parameter_category.store');
	Route::get('posisi/parameter_category/{id_posisi}/{id}/edit','Admin\ParameterCategoryPositionController@edit')
		   ->name('admin.posisi.parameter_category.position.edit');
	Route::put('posisi/parameter_category/{id_posisi}/{id}/edit','Admin\ParameterCategoryPositionController@update')
		   ->name('admin.posisi.parameter_category.position.update');
	Route::delete('posisi/parameter_category/{id}','Admin\ParameterCategoryPositionController@destroy')
		   ->name('admin.posisi.parameter_category.position.destroy');

	/**
     * route parameter posisi
     */
    Route::get('posisi/parameter/{id_posisi}/{id_kategori}','Admin\ParameterPositionController@create')
		   ->name('admin.posisi.parameter');
	Route::post('posisi/parameter/{id_posisi}/{id_kategori}','Admin\ParameterPositionController@store')
		   ->name('admin.posisi.parameter.store');
	Route::get('posisi/parameter/{id_posisi}/{id_kategori}/{id}/edit','Admin\ParameterPositionController@edit')
		   ->name('admin.posisi.parameter.edit');
	Route::put('posisi/parameter/{id}/update','Admin\ParameterPositionController@update')
		   ->name('admin.posisi.parameter.update');
	Route::delete('posisi/parameter/{id}','Admin\ParameterPositionController@destroy')
		   ->name('admin.posisi.parameter.destroy');

	/**
	 * route kaategori parameter fisik
	 */
	Route::get('fisik/parameter_category/{id_fisik}','Admin\ParameterCategoryFisikController@create')
		   ->name('admin.fisik.parameter_category.fisik');
	Route::post('fisik/parameter_category/store/{id_posisi}','Admin\ParameterCategoryFisikController@store')
		   ->name('admin.fisik.parameter_category.store');
	Route::get('fisik/parameter_category/{id_posisi}/{id}/edit','Admin\ParameterCategoryFisikController@edit')
		   ->name('admin.fisik.parameter_category.fisik.edit');
	Route::put('fisik/parameter_category/{id_posisi}/{id}/edit','Admin\ParameterCategoryFisikController@update')
		   ->name('admin.fisik.parameter_category.fisik.update');
	Route::delete('fisik/parameter_category/{id}','Admin\ParameterCategoryFisikController@destroy')
		   ->name('admin.fisik.parameter_category.fisik.destroy');

	/**
     * route parameter fisik
     */
    Route::get('fisik/parameter/{id_fisik}/{id_kategori}','Admin\ParameterFisikController@create')
		   ->name('admin.fisik.parameter');
	Route::post('fisik/parameter/{id_fisik}/{id_kategori}','Admin\ParameterFisikController@store')
		   ->name('admin.fisik.parameter.store');
	Route::get('fisik/parameter/{id_fisik}/{id_kategori}/{id}/edit','Admin\ParameterFisikController@edit')
		   ->name('admin.fisik.parameter.edit');
	Route::put('fisik/parameter/{id}/update','Admin\ParameterFisikController@update')
		   ->name('admin.fisik.parameter.update');
	Route::delete('fisik/parameter/{id}','Admin\ParameterFisikController@destroy')
		   ->name('admin.fisik.parameter.destroy');

	/**
	 * route report staff
	 */
	Route::get('/reportstaffs/stores/','Admin\ReportStaffController@stores')->name('admin.reportstaffs.stores');
	Route::get('/reportstaffs/{code}','Admin\ReportStaffController@index')->name('admin.reportstaffs.index');
	Route::get('/reportstaffs/edit/{id}','Admin\ReportStaffController@edit')->name('admin.reportstaffs.edit');
	Route::put('/reportstaffs/update/{id}','Admin\ReportStaffController@update')->name('admin.reportstaffs.update');


	/**
	 * route report fisik store
	 */
	Route::get('/reportfisikstores/stores/','Admin\ReportFisikStoreController@stores')->name('admin.reportfisikstores.stores');
	Route::get('/reportfisikstores/{code}','Admin\ReportFisikStoreController@index')->name('admin.reportfisikstores.index');
	Route::get('/reportfisikstores/edit/{id}','Admin\ReportFisikStoreController@edit')->name('admin.reportfisikstores.edit');
	Route::put('/reportfisikstores/update/{id}','Admin\ReportFisikStoreController@update')->name('admin.reportfisikstores.update');

	/**
	 * hapus file attachment
	 */
	Route::delete('file/staff/destroy/{id}','Admin\ReportStaffController@destroyFile')
		   ->name('admin.file.staff.destroy');

	/**
	 * Route untuk setting web report
	 */
	// Route::put('update/websetting',[
	//     'as'    =>  'admin.update.websetting',
	//     'uses'  =>  'Admin\WebSettingController@update'
	// ]);
	
	/**
	 * Route parameter nasional
	 */
	Route::get('/reportparameter/','Admin\ReportParameterController@index')->name('admin.reportparameter.index');
	Route::put('/reportparameter/storeNasional','Admin\ReportParameterController@storeNasional')->name('admin.reportparameter.storeNasional');
	Route::get('/reportparameter/rbh/{id_rbh}','Admin\ReportParameterController@getRbh')->name('admin.reportparameter.getrbh');
	Route::put('/reportparameter/storeRbh/{code}','Admin\ReportParameterController@storeRbh')->name('admin.reportparameter.storeRbh');

	Route::get('/reportnasionalrbh/','Admin\ReportNasionalRBHController@edit')->name('admin.reportnasionalrbh.edit');
	Route::post('/reportnasionalrbh/','Admin\ReportNasionalRBHController@store')->name('admin.reportnasionalrbh.edit');
	

});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});	

Auth::routes();

Route::group(['middleware' =>'cekrolesistem'], function () {
	
	Route::get('/home', 'HomeController@index');

});

app/Models/ReportStaff.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ReportStaff extends Model
{
    protected $table = 'report_staffs';

    protected $fillable = [
        'report_id',
        'staff_id',
        'summary',
        'score',
        'score_individu',
    ];

    /**
     * @param $report
     * @param $staff
     *
     * @return \Illuminate\Database\Eloquent\Model|null|static
     */
    public static function setStaff($report, $staff)
    {
        return self::where('staff_id', '=', $staff->id)
                    // ->where('report_id', '=', $report->id)
                    ->first();
    }

    public function staff()
    {
        return $this->belongsTo('App\Models\Staff','staff_id');
    }

    public function report()
    {
        return $this->belongsTo('App\Models\Report','report_id');
    }

}

resources/views/admin/report_staff/form.blade.php
@extends('admin.layouts.app')

@section('css')
  <link href="{{  asset('admin/css/datatables.bootstrap.css') }}" rel="stylesheet">
  <link href="{{  asset('admin/css/sweetalert2.css') }}" rel="stylesheet">
  <link href="{{  asset('admin/css/fileinput.min.css') }}" rel="stylesheet">


@endsection

@section('content')
	<section class="content">
		

        <div class="row">
	        <div class="col-md-12">

	          {{-- Untuk Pesan Error --}}
	          @if (count($errors) > 0)
	              <div class="alert alert-danger">
	                  <ul>
	                      @foreach ($errors->all() as $error)
	                          <li>{{ $error }}</li>
	                      @endforeach
	                  </ul>
	              </div>
	          @endif

	        </div>
	    </div>

	    <div class="row">
        
        	<div class="col-md-12">
          		<div class="box box-primary">
            
           {!!  Form::model($staff, array('method' => 'put', 'route' => array('admin.reportstaffs.update', $staff->id), 'files'=> true)) !!}
            
	              <div class="box-body">
	                  
		                  <div class="form-group">
		                      {!! Form::label('name', 'Store', array('class'=>'')) !!}
		                      {!! Form::text('name', $staff->store->name, array('class'=>'form-control','readonly')) !!}
		                  </div>

		                  <div class="form-group ">
		                       {!! Form::label('posisi', 'Posisi', array('class'=>'')) !!}
		                       {!! Form::text('posisi', $staff->position->name, array('class'=>'form-control','readonly')) !!}
		                  </div>

		                  <div class="form-group">
		                      {!! Form::label('kode_staff', 'Kode Staff', array('class'=>'')) !!}
		                      {!! Form::text('kode_staff', old('kode_staff'), array('class'=>'form-control','readonly')) !!}
		                  </div>

		                  <div class="form-group">
		                      {!! Form::label('name', 'Nama', array('class'=>'')) !!}
		                      {!! Form::text('nama', old('nama'), array('class'=>'form-control','readonly')) !!}
		                  </div>

		                  <div class="form-group">
		                      <label for="gender">Gender</label>
		                      {!! Form::text('gender', $staff->gender == 1 ? 'pria':'wanita', array('class'=>'form-control','readonly')) !!}
		                  </div>

		                   <div class="form-group ">
			                    <label class="control-label " for="score">
			                        Score
			                    </label>
			                    <div class="input-group">
			                        <div class="input-group-addon">
			                            <i class="fa fa-book">
			                            </i>
			                        </div>
			                        <input class="form-control" id="score" name="score" type="text" value="{!! $staff->reportstaff->score or '' !!}">
			                    </div>
			                </div>

			                <div class="form-group">
		                      {{ Form::label('content', 'Konten', array('class'=>'control-label')) }}
                              {{ Form::textarea('summary', ($staff['reportstaff']) ? $staff['reportstaff']->summary : '', array('class'=>'ckeditor')) }}
		                    </div>

		                    {{--untuk mendapatkan posisi parameter category dari posisi yang dipilih staff--}}
                        	@if(count($staff['position']['parameter_category']))
                            	@foreach($staff['position']['parameter_category'] as $key => $category)
									<div class="form-group">
	                                    <label for="{{ $category->category }}">
	                                        <h2> Kategori - {{ $category->category }} </h2>
	                                    </label>
										
										<br>
										
										<?php

											$value = App\Models\ReportPerformanceStaff::where('staff_id', '=', $staff->id)
                                                            ->where('category_id', '=', $category->id)
                                                            ->where('report_id', '=', \Session::get('report')->id)
                                                            ->first(); 

										?>
										
										<!--
										<div class="form-group">
					                      {{-- <label for="gender">Input Nilai {{ $category->category }}</label> --}}
					                      {{-- {!! Form::text('performance['.$category->id.']', $value ? $value->score : '', array('class'=>'form-control')) !!} --}}
					                    </div>-->		



	                                    <?php $parameter = $category['parameter_data'];  ?>

	                                    @if(count($parameter))
											<table class="table table-bordered table-hover">
												@foreach($parameter as $param)
													<?php

													    $ada_gender   = false;
	                                                    $parameter_gender = 0;

	                                                    foreach ($param['parameter_gender']->toArray() as $value) {
												            if($value['gender'] == $staff->gender) {
												                $ada_gender = true;
												                break;
												            }
												        }

	                                                ?>

	                                                  @if($ada_gender)

														  <?php 
														   $value = App\Models\ParameterReportPosition::where('staff_id', '=', $staff->id)
                                                            ->where('position_parameter_data_id', '=', $param->id)
                                                            ->where('report_id', '=', Session::get('report')->id)
                                                            ->first(); ?>

                                                            <tr>
		                                                        <td class="text-center" style="width: 10%">
		                                                            {{ Form::select('parameter['.$param->id.']', [0 => 'N/A', 1 => 'Ya', 2 => 'Tidak'], ($value) ? $value->status : null, ['class' => 'form-control']) }}
		                                                        </td>

		                                                        <td style="width: 45%"> <strong>{!! $param->kode_atribut !!}</strong> - {{ $param->text }}</td>
		                                                        <td class="text-center" style="width: 45%">
		                                                            {{ Form::text('komentar['.$param->id.']',old('komentar', ($value) ? $value->comment : null), array('class' => 'form-control', 'placeholder' => 'Komentar...', 'maxlength' => 255)) }}
		                                                        </td>
		                                                    </tr>
	                                                @endif

												@endforeach
											</table>
	                                    @else
	                                        <div class="alert alert-warning alert-dismissable" style="margin-top: 20px">
	                                            <i class="glyphicon glyphicon-warning-sign"></i>
	                                            Belum ada parameter untuk kategori ini.
	                                        </div>
	                                    @endif

                                    </div>    
                        	    @endforeach
	                        @else
	                            <div class="alert alert-warning alert-dismissable" style="margin-top: 30px">
	                                <i class="glyphicon glyphicon-warning-sign"></i>
	                                Belum ada kategori parameter untuk posisi ini.
	                            </div>
	                        @endif

	                        <div class="form-group">
		                      <label for="gender">File Multimedia</label>
		                      {!! Form::file('file',['class'=>'form-control']); !!}
		                    </div>


	              </div>
	              <!-- /.box-body -->

	              <div class="box-footer">
	                <button type="submit" class="btn btn-primary">Submit</button>
	                <a href="{!! route('reports.index') !!}" class="btn btn-default">Batal</a>
	              </div>

	            {!! Form::close() !!}

	            </div>
	          </div> 	

	      </div>
		
		
		<div class="row">
			<div class="col-md-12">
				<div class="box box-primary">
					@if(count($files))
						<table class="table table-bordered" id="stores-table">
	                        <meta name="csrf-token" content="{{ csrf_token() }}">
	                        <thead>
	                        <tr>
	                            <th>Nama File</th>
	                            <th>Categori</th>
	                            <th>Action</th>
	                        </tr>
	                        </thead>
	                        <tbody>
	                            @foreach($files as $file)
	                                <tr>
	                                    <td>{{ $file->filename  or '-' }}</td>
	                                    <td>{{ $file->filetype  or '-' }}</td>
	                                    <td style="width: 80px;">
	                                        <a href="#" data-target="{{ route('admin.file.staff.destroy', [$file->id]) }}" class="btn btn-danger btn-xs confirmation" data-toggle="tooltip" data-original-title="Hapus" data-container="body" onclick="hapusData(this)">
                                            <i class="fa fa-trash-o"></i>
                                            </a>
	                                    </td>
	                                </tr>
	                            @endforeach
	                        </tbody>
	                    </table>
					@else
						@include('admin.layouts.partials.alertWarning')
					@endif
				</div>
			</div>
		</div>

	</section>
@endsection

@section('js')
  {{-- <script src="{!!  asset('admin/js/jquery.form.min.js')  !!}"></script> --}}
  <script src="{!!  asset('admin/js/ckeditor/ckeditor.js')  !!}"></script>
  <script src="{{ asset('admin/js/sweetalert2.min.js') }}"></script>
  <script src="{{ asset('admin/js/confirm.js') }}"></script>
@endsection

resources/views/admin/report_staff/index.blade.php
@extends('admin.layouts.app')

@section('css')
  <link href="{{  asset('admin/css/datatables.bootstrap.css') }}" rel="stylesheet">
  <link href="{{  asset('admin/css/sweetalert2.css') }}" rel="stylesheet">


@endsection

@section('content')
    <!-- Main content -->
    <section class="content">
      
      <div class="row">
        <div class="col-md-12">
          {!! Breadcrumbs::render('breadcrumb') !!}
        </div>
      </div>

       <div class="row">
        <div class="col-md-12">

          {{-- Untuk Pesan Sukses --}}
          @if(Session::has('alert-success'))
              <div class="alert alert-success">
                    {{ Session::get('alert-success') }}
                </div>
          @endif

        </div>
      </div>
       <div class="row">
       	
       	<div class="col-md-12">
            <div class="nav-tabs-custom">
             <ul class="nav nav-tabs">
                <li class="active"><a href="#datatable" data-toggle="tab"> <i class="fa fa-table" aria-hidden="true"></i> Datatable</a></li>
                {{-- <li><a href="#excel" data-toggle="tab"><i class="fa fa-file-excel-o" aria-hidden="true"></i> Upload Via Excel</a></li> --}}
             </ul>
             <div class="tab-content">
                <div class="tab-pane active" id="datatable">
                   @if(count($staffs))
                    <table class="table table-bordered" id="stores-table">
                        <meta name="csrf-token" content="{{ csrf_token() }}">
                        <thead>
                        <tr>
                            <th  style="width: 100px;">Ava</th>
                            <th  style="width: 100px;">Kode Staff</th>
                            <th>Nama</th>
                            <th>Posisi</th>
                            <th>Gender</th>
                            <th>Score</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                            @foreach($staffs as $staff)
                                <tr>
                                    <td class="text-center">
                                      @if($staff->ava)
                                        <img src="{{ asset('attachments/ava_staff/table').DIRECTORY_SEPARATOR.$staff->ava }}" class="user-image img-circle" alt="{{ $staff->nama }}">
                                      @else
                                        <p class="text-yellow">Photo belum diupload</p>
                                      @endif
                                    </td>
                                    <td>{{ $staff->kode_staff  or '-' }}</td>
                                    <td style="width: 86px;">{{ $staff->nama or '-' }}</td>
                                    <td style="width: 86px;">{{ $staff->position->name or '-' }}</td>
                                    <td style="width: 86px;">
                                      {!! $staff->gender == 1 ? 'pria' : 'wanita' !!}
                                    </td>
                                    <td style="width: 86px;">{{ $staff->reportstaff->score or 'Nilai Belum diupload' }}</td>
                                    <td style="width: 80px;">
                                        <a href='{{ route('admin.reportstaffs.edit', [$staff->id]) }}' class="btn btn-success btn-xs" data-toggle="tooltip" data-original-title="Edit" data-container="body">
                                        <i class="fa fa-edit" aria-hidden="true"></i>
                                        </a>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                    @else
                        @include('admin.layouts.partials.alertWarning')
                    @endif
                </div>
                
                <!-- /.tab-pane -->
                <div class="tab-pane" id="excel">
                  
                </div>
                <!-- /.tab-pane -->
             </div>
             <!-- /.tab-content -->
          </div>
       	</div>

       </div>

    </section><!-- /.content -->

@endsection

@section('js')
  <!-- DataTables -->
    <script src="{{ asset('admin/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('admin/js/datatables.bootstrap.js') }}"></script>
    <!-- jquery confirm -->
    <script src="{{ asset('admin/js/sweetalert2.min.js') }}"></script>
    <script src="{{ asset('admin/js/confirm.js') }}"></script>

    <script>
        $(document).ready(function() {
            $('#stores-table').DataTable();
        } );
    </script>


@endsection